# PWskills 16th Feb Assignment Sol

###  Q1. What is a database? Differentiate between SQL and NoSQL databases.

### Answer:
A database is an organized collection of structured information, or data, typically stored electronically in a computer system.

Difference:

SQL (Structured Query Language) and NoSQL (Not only SQL) are two different types of database management systems. Here are the key differences between SQL and NoSQL:

Data Model:

SQL: SQL databases use a structured data model based on tables with predefined schemas. Data is organized into rows and columns, and relationships between tables are established using foreign keys.
NoSQL: NoSQL databases use various data models, such as key-value pairs, documents, graphs, or wide-column stores. They provide more flexibility in handling unstructured or semi-structured data.
Schema:

SQL: SQL databases have a fixed schema, meaning the structure of the database, including tables, columns, and data types, is defined in advance. Changes to the schema can be time-consuming and require careful planning.
NoSQL: NoSQL databases are schema-less or have a flexible schema. They allow for dynamic and ad-hoc changes to the data structure, which can be beneficial in scenarios where data requirements evolve rapidly.
Scalability:

SQL: SQL databases typically follow a vertical scaling approach, where hardware resources are increased to handle larger workloads. This approach has limitations in terms of scalability.
NoSQL: NoSQL databases are designed to scale horizontally by distributing data across multiple servers or clusters. They can handle high volumes of traffic and provide better scalability for large-scale applications.
Query Language:

SQL: SQL databases use SQL as the standard query language for defining and manipulating the data. SQL provides a declarative approach where you specify what data you want rather than how to retrieve it.
NoSQL: NoSQL databases have their query languages specific to the data model they use. These query languages can vary between different NoSQL databases and may not be as standardized as SQL.
ACID Compliance:

SQL: SQL databases traditionally adhere to ACID (Atomicity, Consistency, Isolation, Durability) properties, which ensure data integrity and transactional consistency. They are suitable for applications that require strict consistency and transactional support.
NoSQL: NoSQL databases often relax some ACID properties to achieve higher scalability and performance. They prioritize availability and partition tolerance (known as the CAP theorem) over strict consistency. However, some NoSQL databases offer varying levels of ACID compliance.
Use Cases:

SQL: SQL databases are commonly used in applications that require complex queries, structured data, and transactions, such as financial systems, e-commerce platforms, and relational data management.
NoSQL: NoSQL databases excel in handling large volumes of unstructured or semi-structured data, rapid development, and scalability. They are often used in real-time analytics, content management systems, social networks, and IoT applications.

### What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

### Answer: 
DDL stands for Data Definition Language. It is a subset of SQL (Structured Query Language) used to define and manage the structure of a database and its objects, such as tables, views, indexes, and constraints. DDL statements are responsible for creating, modifying, and deleting database objects.

Explanation of CREATE, DROP, ALTER and TRUNCATE:


1.CREATE:
The CREATE statement is used to create a new database object. It can be used to create tables, views, indexes, or other objects depending on the database system.

CREATE TABLE Customers (

    CustomerID INT PRIMARY KEY,
    
    FirstName VARCHAR(50),
    
    LastName VARCHAR(50),
    
    Email VARCHAR(100)
);

2.DROP: 


The DROP statement is used to remove a database object, such as a table, view, or index, from the database.


Code: 

DROP TABLE Customers;


3.ALTER:
The ALTER statement is used to modify the structure of an existing database object. It can be used to add, modify, or drop columns, constraints, or indexes.

Example: Adding a column to a table

ALTER TABLE Customers

ADD Phone VARCHAR(15);


4.RUNCATE:
The TRUNCATE statement is used to remove all data from a table, but keeps the table structure intact. It is a faster alternative to deleting all rows individually.

Example: Truncating a table

TRUNCATE TABLE Customers;

### Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

### Answer:
DML stands for Data Manipulation Language. It is a subset of SQL (Structured Query Language) used to manipulate data within a database. DML statements are responsible for inserting, updating, and deleting data in database tables.

Expalanation:

1. INSERT:
The INSERT statement is used to add new data into a table. It allows you to specify the values for each column or insert data from another table.

Example 1: Inserting values into specific columns

INSERT INTO Customers (CustomerID, FirstName, LastName, Email)

VALUES (1, 'John', 'Doe', 'johndoe@example.com');

2. UPDATE:
The UPDATE statement is used to modify existing data in a table. It allows you to update specific columns with new values based on specified conditions.

Example: Updating a specific row

UPDATE Customers

SET Email = 'newemail@example.com'

WHERE CustomerID = 1;

3. DELETE:
The DELETE statement is used to remove specific rows or all rows from a table.

Example 1: Deleting specific rows

DELETE FROM Customers

WHERE CustomerID = 1;

### Q4.What is DQL? Explain SELECT with an example.

### Answer:
DQL stands for Data Query Language. It is a subset of SQL (Structured Query Language) used to retrieve data from a database. DQL statements are primarily focused on querying and retrieving data from tables based on specified conditions.

The most commonly used DQL statement is SELECT. It allows you to retrieve data from one or more tables, apply filters, perform calculations, and sort the results.

Here is an explanation of the SELECT statement with an example:

SELECT:
The SELECT statement is used to retrieve data from a database table or tables. It allows you to specify the columns to be retrieved, apply filters, perform calculations, and control the order of the results.

Example:

SELECT FirstName, LastName, Salary

FROM Employees

ORDER BY Salary DESC;

### Q5. Explain Primary Key and Foreign Key.

### Answer:

Primary Key:
A primary key is a column or a set of columns in a database table that uniquely identifies each row or record. It provides a way to ensure the integrity and uniqueness of data within a table. Here are the key characteristics of a primary key:

Uniqueness: Every value in the primary key column(s) must be unique. No two rows in the table can have the same primary key value.

Non-nullability: A primary key column(s) cannot contain null values. Each row must have a valid value in the primary key column(s).

Immutable: The primary key value(s) should not change over time. It provides a stable identifier for a record throughout its lifetime.

Single-valued: Each row in the table can have only one primary key value. It ensures that each record is uniquely identified.

A primary key can be defined when creating a table using the CREATE TABLE statement. It is often created on a column or a combination of columns that uniquely identify the records. Primary keys are essential for enforcing data integrity, enabling efficient indexing, and establishing relationships with other tables.

Foreign Key:
A foreign key is a column or a set of columns in a database table that establishes a link or relationship between two tables. It creates a connection between the primary key of one table (referenced table) and a column(s) in another table (referencing table). Here are the key characteristics of a foreign key:

Referential Integrity: A foreign key maintains referential integrity by ensuring that values in the referencing table match values in the referenced table's primary key.

Relationship: The foreign key represents a relationship between the tables, where the values in the referencing column(s) are associated with the corresponding values in the referenced table's primary key column(s).

Integrity Constraints: Foreign keys can enforce constraints such as CASCADE, SET NULL, or SET DEFAULT actions to maintain data integrity when the referenced primary key is updated or deleted.

Multiple Occurrences: In a referencing table, multiple rows can have the same foreign key value, establishing a relationship with the corresponding primary key values in the referenced table.

Foreign keys are used to establish relationships and enforce data integrity rules between tables in a relational database.

### Q5. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

### Answer:

First, weq need to install the package using pip:

pip install mysql-connector-python

Here's an example code that demonstrates how to connect Python to MySQL and perform a simple query:

import mysql.connector

#Connect to MySQL
mydb = mysql.connector.connect(

  host="localhost",
  
  user="your_username",
  
  password="your_password",
  
  database="your_database"
)

#Create a cursor object
cursor = mydb.cursor()

#Execute a query
cursor.execute("SELECT * FROM customers")

#Fetch all rows from the result
results = cursor.fetchall()

#Print the fetched rows
for row in results:

  print(row)

#Close the cursor and connection
cursor.close()

mydb.close()





1.cursor() method:
The cursor() method is used to create a cursor object that allows you to execute SQL statements and fetch the results. It is called on the database connection object (mydb in the example).

2.execute() method:
The execute() method is used to execute an SQL query or statement. It takes the SQL query as a parameter and performs the operation on the database. In the example, the execute() method is used to execute the SELECT query ("SELECT * FROM customers"). The result of the query is stored in the cursor object.

Note: The execute() method can also take parameters to dynamically pass values into the SQL statement, which helps prevent SQL injection attacks.